[package]
name = "enable-ansi"
version = "0.1.5"
edition = "2024"
description = "tiny helper function to enable virtual terminal processing (ansii colors) in build without cargo"
license = "MIT"
repository = "https://github.com/Soreg404/enable-ansi.git"

[[bin]]
name = "pretty_print"
path = "pretty_print.rs"

[lib]
name = "enable_ansi"
path = "enable_ansi.rs"
