[package]
name = "enable-ansi"
version = "0.1.3"
edition = "2024"
description = "tiny helper function to enable virtual terminal processing (ansii colors) in build without cargo"
license = "MIT"

[[bin]]
name = "pretty_print"
path = "pretty_print.rs"

[lib]
name = "enable_ansi"
path = "enable_ansi.rs"
